### ISSUE TITLE
Offline Messaging is Unreliable

### ISSUE THREAD

**Issue by subliun** [Antox/Antox#107]
Only mark a message as sent after we have received a read receipt rather than assuming it has been sent.

**Comment by toxtox** [comment]
Yes, as long as the "green online dot" of the recipient is shining, the messages are in a dark violet speech bubble (should be a light violet speech bubble), even if the recipient is already offline.
BUT the BIGGER PROBLEM is that the unsent messages are not sent when the recipient is online again (even the messages in the light violet speech bubbles are not sent).
This missing feature is called "Faux offline messaging" in the PC client "qTox" (look at qTox "settings -> General")
