### ISSUE TITLE
"Failed to load a required library. Unable to create non-incognito accounts"

### ISSUE THREAD

**Issue by donjan** [Antox/Antox#129]
This is already tracked at https://github.com/Astonex/Antox/issues/678, but this repo seems to be more active.

Trying to register a user, instead of using incognito, gives the error in the title. It also sometimes crashes the app (force close dialog).

Specs in my case:
Android 2.3.5 on HTC Desire S S510e, stock Sense 3.0 ROM (rooted).

**Comment by subliun** [comment]
You're using the latest version? From either https://antox.me/fdroid/repo or the new link on the G+ page?

**Comment by donjan** [comment]
I'm getting "Error getting index file from https://antox.me/fdroid/repo" after adding and trying to update the (unsigned) F-Droid repo.

Using the G+ page download (https://play.google.com/store/apps/details?id=chat.tox.antox) gives me a "package file invalid" error on my phone, which I can't get rid off with the usual cache clearing methods (even reverting to the Market app). Same with hitting update on my current Antox entry in the Play Store.

Is there a direct download for the apk?

**Comment by subliun** [comment]
https://antox.me/fdroid/repo/antox.apk

Though that won't update automatically. I'm not sure why the other methods aren't working for you. :-/

**Comment by donjan** [comment]
Thanks, this helped with debugging. Here's the relevant logcat section after 'adb install':

E/PackageManager( 1392): Package chat.tox.antox has mismatched uid: 10125 on disk, 10128 in settings
D/installd( 1277): DexInv: --- BEGIN '/data/app/chat.tox.antox-1.apk' ---
I/PackageManager( 1392): Linking native library dir for /data/app/chat.tox.antox-1.apk
D/dalvikvm(13067): creating instr width table
E/dalvikvm(13067): LinearAlloc exceeded capacity (5242880), last=5980
E/dalvikvm(13067): VM aborting
[ ... dexopt libdvm.so dump ... ]
W/installd( 1277): DexInv: --- END '/data/app/chat.tox.antox-1.apk' --- status=0x000b, process failed
E/installd( 1277): dexopt failed on '/data/dalvik-cache/data@app@chat.tox.antox-1.apk@classes.dex' res = 11

Not sure if the mismatched UID matters, but the linearAlloc on Gingerbread crashes. Googling implies a fixed size limit and suggestions like "splitting up the class" (http://www.birbit.com/how-to-solve-linearalloc-problem/) or using multidex support, or ProGuard/DexGuard (although I assumed ProGuard is already used?).

Hm, could you maybe provide a Antox <=0.23.25 apk so I can verify it's not a misconfiguration issue on my part?
I originally had a binary from the old tox.im domain, then at some point updated to 0.23.25 via the Play Store web interface, tried (and failed) updating again this week (via the web interface and adb). Currently I have removed all Antox versions from my phone, deleted the /data/system/ cache entry and file and hopefully all other traces, and don't want to install some random googled Antox apks.

**Comment by rabfulton** [comment]
I also get "package file invalid"  using the G+ link. Android 2.3 Samsung Galaxy S. I originally tried to update the older version I had installed, but no new updates were available so uninstalled and then tried G+ link.
