### ISSUE TITLE
tox: URLs are case-sensitive, lowercase causes crash on friend request

### ISSUE THREAD

**Issue by kyanha** [Antox/Antox#219]
If, for whatever reason, you must try to retype a tox: URL, if you don't end up typing it uppercase Antox will crash on the attempt to send the friend request.  The string "tox:" at the beginning must be lowercase, though.

This occurs when the lowercase tox: URL is converted to a QR code and scanned.  I have not tried lowercase Tox IDs in other circumstances (getting this one ID imported was already headache-inducing).

Suggested fix: Convert the Tox ID to uppercase before acting on it.

**Comment by subliun** [comment]
Addresses with lowercase letters should be rejected now, though I didn't test it. Try the latest build.

**Comment by ProMcTagonist** [comment]
Is there a reason we can't convert to uppercase?

**Comment by subliun** [comment]
@ProMcTagonist I think it's better that we enforce a standard Tox ID format, having two acceptable standards could confuse users.

**Comment by kyanha** [comment]
It's a hexadecimal number. Most programmers are used to hex numbers being case-insensitive.

**Comment by subliun** [comment]
@kyanha the case of the 'tox:' at the front is not enforced. TOX: is accepted.

**Comment by kyanha** [comment]
Effectively closed with #388 by patch #420 .
