### ISSUE TITLE
pressing back button on conversation opened by notification closes activity

### ISSUE THREAD

**Issue by agilob** [Antox/Antox#223]
1. Get message from A
2. Click on notification
3. Shows conversation
4. Press back
5. Desktop - I expected list of contacts

**Comment by subliun** [comment]
I wondered how long it would take until somebody found this. :-/
I've tried to fix it but it didn't work. I suppose I'll try again.

**Comment by agilob** [comment]
I found this long time ago, but seemed to be so obvious that didn't report :>
