### ISSUE TITLE
Fdroid repo not alligned with play store

### ISSUE THREAD

**Issue by svalo** [Antox/Antox#239]
The latest antox version present on the new repo is behind the one on playstore. For me playstore reports 0.23.308 while the one on Fdroid is 0.23.301

**Comment by svalo** [comment]
Is this on purpose or some automagic is not working?
How the f-droid repo is managed?

**Comment by wiiaam** [comment]
Currently the F-Droid repo is not being automatically updated as there are no scripts to automatically pull the apk from the build servers. @Zer0-One is fixing this and the repo will be updated soon

**Comment by svalo** [comment]
>  @Zer0-One is fixing this and the repo will be updated soon

Great! Thanks! may I be of any help?

**Comment by Zer0-One** [comment]
@svalo Thanks, but I think we've got it. Our F-Droid repo is new, and we were lacking some of the magical server-side glue, but I've just written the script we needed. All that's left to do is iron out one or two issues we're having with the fdroid tools, and things will be running smoothly. Check back in a few days for progress.

**Comment by svalo** [comment]
Great!

**Comment by svalo** [comment]
It worked for few days but as of now it's not aligned again

**Comment by Zer0-One** [comment]
@svalo alright, problem should be solved for good now.
