### ISSUE TITLE
Could not install Andoid 2.3.6

### ISSUE THREAD

**Issue by samersuha** [Antox/Antox#241]
Cant install on 2.3.6, error: INSTALL_FAILED_DEXOPT

**Comment by wiiaam** [comment]
Where are you installing the app from? (play store, fdroid, etc)

**Comment by samersuha** [comment]
I own a phone shop I have tried all brands. Nothing with android 2.3.6 accept to install the apk, I have tried playstore version, fdroid version . Also I tried compiling from source. No luck

**Comment by wiiaam** [comment]
Well, its finally happened. The dex file in the apk is too large for android 2.3.
There is a fix for this that splits it into multiple files, but Antox will be dropping support for 2.3 soon anyway as libraries are needed for A/V that are incompatable with 2.3

**Comment by VerdonTrigance** [comment]
Is there any alternative libraries for A/V that works on Android 2.3 ?
May be some previous releases (branches) support Android 2.3?

**Comment by zoff99** [comment]
@VerdonTrigance what phone do you have? on 2.3 it will be hard to do videocalling anyway.
i am afraid you need to get a new china android device. is there a reason why you need Android 2.3?

**Comment by VerdonTrigance** [comment]
@zoff99 I have xperia mini pro. As you can imagine it's hard to find similar phone.
Is it possible to make branch without video calls that support such old Android?

**Comment by imShara** [comment]
@VerdonTrigance, it's not that you ask, but there is official 4.0 android for xperia mini pro.

**Comment by VerdonTrigance** [comment]
@imShara I know it, but it's too heavy for such device. I prefer Android 2.3. So, here is no any branch for low Android version?
