### ISSUE TITLE
Excessive data usage even without sending messages

### ISSUE THREAD

**Issue by timonti** [Antox/Antox#243]
Even without sending or receiving a single messages data consumed excessively.

Using antox from the playstore (0.23.31*)

- UDP is disabled.

![data consumed](https://cloud.githubusercontent.com/assets/1318075/12580141/12ebaa80-c453-11e5-9f2e-242c4a1271b5.png)
![empty messages](https://cloud.githubusercontent.com/assets/1318075/12580142/12f20786-c453-11e5-89a0-03f982d70e5a.png)

**Comment by LuccoJ** [comment]
This is a problem with toxcore, not Antox specifically, which was being discussed at https://github.com/irungentoo/toxcore/issues/1251 and is now being discussed at https://github.com/irungentoo/toxcore/issues/1501

**Comment by wiiaam** [comment]
Also discussed in issue https://github.com/Antox/Antox/issues/6
