### ISSUE TITLE
Crash antox whith chat user

### ISSUE THREAD

**Issue by SergeyDjam** [Antox/Antox#245]
I'm setup antox.apk 31.01.2016, add user, and message and her crash antox

QUMO Altair 702, Android 4.2.2

**Comment by wiiaam** [comment]
Yeah this was a bug that slipped in breaking messaging for clients not being run on lollipop devices
Should be fixed now in the latest version (0.23.327)

**Comment by agilob** [comment]
Please make a release of 0.23.327 in fdroid.

**Comment by SergeyDjam** [comment]
Yes, and add release from name pakcage...

**Comment by SergeyDjam** [comment]
Build to 02/02/2016 on fdroid fix this problem. 

Phank you
