### ISSUE TITLE
Support encrypted profiles

### ISSUE THREAD

**Issue by subliun** [Antox/Antox#249]

**Comment by wiiaam** [comment]
Hmm maybe

**Comment by subliun** [comment]
Wouldn't it be nice

**Comment by wiiaam** [comment]
It'll break auto signin though

**Comment by subliun** [comment]
Not if you do it right

**Comment by wiiaam** [comment]
>keep their password stored in the db
great idea

**Comment by subliun** [comment]
>hasn't read the encryption docs
now there's a great idea

**Comment by wiiaam** [comment]
can you read them to me before i go to sleep? i love a good fairytale before i head to dreamland

**Comment by subliun** [comment]
just save the key you wiiaam

**Comment by wiiaam** [comment]
salty

**Comment by wiiaam** [comment]
Feature added
