### ISSUE TITLE
[Request future] Antox sand emoticons and stickers

### ISSUE THREAD

**Issue by SergeyDjam** [Antox/Antox#250]
Hello. Please, add emoticons and stickers sending dialog...

**Comment by wiiaam** [comment]
Any emoji you type with your keyboard can be sent

As for stickers they are something I'd like to see in tox, although we would rather irungentoo spent his time on new groupchats and increasing the stability before adding fluff to it. 
A mockup for stickers has been made and can be found [here](https://wiki.tox.chat/developers/feature_ideas/stickers)

**Comment by ProMcTagonist** [comment]
Why close? It's not resolved yet.

**Comment by wiiaam** [comment]
Because stickers are not a problem for Antox but for toxcore.
Also I'd rather keep the issue tracker for bugs and features I can add, anything else belongs in the toxcore repo

**Comment by subliun** [comment]
Stickers are a problem for Antox; toxcore doesn't need to do anything. Really it's the TCS's problem but nobody likes that so you should just do it.

**Comment by wiiaam** [comment]
>toxcore doesn't need to do anything

Until https://github.com/irungentoo/toxcore/pull/1460 is merged then there's no proper way to sending/receiving stickers. You might as well send someone an image you downloaded from the internet, using the basic file transfer method.

>Really it's the TCS's problem but nobody likes that

Well it's currently the only thing we have for this kind of stuff, and just because you don't like the guy that made it doesn't mean you shouldn't be following it.

**Comment by ProMcTagonist** [comment]
@subliun would you mind sharing the link to the google doc?

**Comment by SergeyDjam** [comment]
Why? Image or stickers or smile what is the difference?

**Comment by metamaker** [comment]
There is no interface for sending smiles from Antox (at least I dont' see it). And normal people don't remember codes for all smiles that they may want send.

**Comment by zoff99** [comment]
we should just use the same lib that "Signal" uses. many apps use that smiley lib

as a starting point:
https://github.com/WhisperSystems/Signal-Android/pull/1656/files
