### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by dopeymeen** [Antox/Antox#251]
Force closes when trying to import profile. On a nexus 5 running 6.0.1

**Comment by wiiaam** [comment]
Check that you have all the required permissions enabled for Antox in settings. 

Unfortunately I cannot test Android 6 support as I don't have an Android 6 phone yet.

**Comment by dopeymeen** [comment]
wow i feel like an idiot. that worked thanks!

**Comment by subliun** [comment]
@wiiaam Emulator

**Comment by wiiaam** [comment]
@subliun Slow

**Comment by subliun** [comment]
@wiiaam Not anymore

**Comment by subliun** [comment]
Duplicate of https://github.com/Antox/Antox/issues/199
