### ISSUE TITLE
add strict proxy settings

### ISSUE THREAD

**Issue by ghostlands** [Antox/Antox#254]
Currently the only way to use Antox with Orbot (Tor) is to set Orbot to proxy Antox, in other words the responsibility for not only routing Antox's traffic, but also upholding the proxy requirement, falls exclusively to Orbot.

The problem with this for Antox users is that if Orbot for whatever reason ceases to function, Antox simply routes its traffic into the clearnet, because Antox never knew or cared that it was using a proxy to begin with. This accidental process more or less immediately unmasks the user, sometimes at random and in the middle of conversations. In this case, which again could occur at random, continuing to use Tor for Antox in that conversation would be pointless, since any adversary observing traffic would by then have substantial data to determine the locations of the conversation's participants.

Strictly enforced proxy settings that fail closed would fix this.

**Comment by wiiaam** [comment]
fixed in https://github.com/Antox/Antox/commit/6abcecc42889febe59e1daa758c10c651bd80296

**Comment by licaon-kter** [comment]
I'm seeing these all the time:
* have Antox with proxy -> Orbot
* something happens ( #224 ?)
* Antox tries to connect via clearnet

Latest F-Droid repo version on 6.0.1

**Comment by ghostlands** [comment]
Yeah the strict part of the bug isn't being adhered to if this is the case. Changed title to be clearer.

@licaon-kter Steps to reproduce please?

**Comment by licaon-kter** [comment]
Use Antox w/ Tor, maybe you change network type, maybe you disconnect and later reconnect, anyway, Antox will try to access the network directly bypassing the proxy.

**Comment by ghostlands** [comment]
@licaon-kter I'm sorry not to be clearer; Tor/Orbot was assumed. By reproduce, I meant where are you seeing the leak? By what means? What tool(s) are you using to find the leaks?

**Comment by licaon-kter** [comment]
Oh, ok [NetGuard](https://github.com/M66B/NetGuard/) as firewall, logging on, notification on access on, Antox blocked, Orbot allowed.

**Comment by ghostlands** [comment]
@licaon-kter Can you post the relevant connections from the log? I'm asking because I don't want to have to install NetGuard right now.

It does look like an interesting firewall though.

**Comment by licaon-kter** [comment]
![Netguard-Antox](https://i.imgur.com/0xC6iEL.jpg)

Let's decode it:
* Antox icon (background service on; proxy socks5; local port 9050)
* Orbot icon (tested connection with Orfox)
* key icon for NetGuard VPN status
* networks cut reddish icons, access blocked
* access attempts, time correlation, reddish colour for blocked

**Comment by ghostlands** [comment]
Excellent, thanks for that.

But I'm guessing that whether this is an actual leak depends both on where NetGuard looks for the attempt and where Antox tries to catch itself, or where it expects to have it's traffic caught.

I don't atm have the ability to look at the code to see if Antox is just trusting some external system proxy hook or something for the redirect. If the latter were the case, it might have been assumed the connections would end up in the right place after leaving the app, but that sure would be a terrible way to strictly ensure proxy.

**Comment by licaon-kter** [comment]
If NetGuard sees the connection it means it already was misplaced by the app.

T is for TCP, I'll add later a view from the NetGuard detailed log.
