### ISSUE TITLE
Import profile option crashes Antox

### ISSUE THREAD

**Issue by alfred300p** [Antox/Antox#259]
Choosing on *Import profile* from the very first screen **crashes** Antox (*Unfortunately, Antox has stopped*).
I installed Antox through F-Droid, following [these instructions](https://tox.chat/download.html#fdroid), on a Nexus 5 with Android 6.0.1.

**Comment by bgaluszka** [comment]
Can confirm, have the same issue on Nexus 5X with Android 6.0.1.

**Comment by alfred300p** [comment]
Ok, this is very likely a duplicate of #258. Sorry I didn't see it first, I only looked for issues related to importing. On the other hand, this one references the problem more directly.
It's a permission problem, and I fixed it by going to `Settings > Apps > Antox > Permissions` and granting `Storage` permission manually.

**Comment by alfred300p** [comment]
I'll close this, since #199 is already open and should fix this.
