### ISSUE TITLE
Add Orbot Support

### ISSUE THREAD

**Issue by ghost** [Antox/Antox#263]
Orbot is Tor on Android. You can download Orbot from FDroid.

**Comment by licaon-kter** [comment]
Was this fixed?

**Comment by wiiaam** [comment]
Yep, orbot uses proxy settings to point network to it

**Comment by licaon-kter** [comment]
But is Orbot started if not running already? I guess that's what the OP meant.

**Comment by wiiaam** [comment]
Not really an antox issue, users should just start it themselves
