### ISSUE TITLE
Where are profile directory?

### ISSUE THREAD

**Issue by KilluaEnki** [Antox/Antox#269]
Hi, sorry where are profile directory to delete my old profile? I cant create profile with same name next reinstalled app ( sorry for my English )

**Comment by wiiaam** [comment]
Reinstalling the app will not remove your toxme account on toxme.io, so you cannot use that name unless you saved the password generated for the toxme account. You can still create an incognito account with the same profile name.

**Comment by KilluaKira** [comment]
mh, Thanks @wiiaam
