### ISSUE TITLE
Add x86-64 support

### ISSUE THREAD

**Issue by wiiaam** [Antox/Antox#272]
Almost done, just need to get https://build.tox.chat/job/tox4j_build_android_x86-64_release/ to build

**Comment by sadmansk** [comment]
This is fantastic news! Have been waiting for this for almost a year now.

**Comment by bozsikarmand** [comment]
Hi!

As a current tester of Antox at Play I can confir that neither the stable nor the Beta works on ASUS ZenFone 2 ZE551ML. (Atom Z3580 model). After start it only shows Antox has stopped.

**Comment by l2dy** [comment]
Does this affect x86-64, x86-32 or both?

**Comment by zoff99** [comment]
@bozsikarmand can you try this beta: https://214-57031623-gh.circle-artifacts.com/0/tmp/circle-artifacts.rFT6bq7/Antox_circleci_f921db238ee2b7055e8222686527243a81683aa5.apk

!! use at your own risk !!

**Comment by wiiaam** [comment]
Added now
