### ISSUE TITLE
build question, gradle

### ISSUE THREAD

**Issue by felix-salfelder** [Antox/Antox#275]
i am not entirely sure, how to build antox, currently trying to figure it out. it seems that running `gradle` in the root directory of the master branch *should* do the trick. but it doesn't... i get

    $ gradle
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '<git_repo_root>/app/build.gradle' line: 24

    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Failed to apply plugin [id 'com.android.application']
        > Gradle version 2.2 is required. Current version is 2.10. If using the gradle wrapper, try editing the distributionUrl in <git_repo_root>/gradle/wrapper/gradle-wrapper.properties to gradle-2.2-all.zip
    [..]

modifying /gradle-wrapper.properties does not change anything, hence i think i am not using "the gradle wrapper". i have

    $ gradle --version
    ------------------------------------------------------------
    Gradle 2.10
    ------------------------------------------------------------
    
    Build time:   2016-03-03 16:14:49 UTC
    Build number: none
    Revision:     <unknown>
    
    Groovy:       2.4.5
    Ant:          Apache Ant(TM) version 1.9.6 compiled on July 6 2015
    JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
    OS:           Linux 4.2.0-1-amd64 amd64

(so yes, it is not 2.2). to me it looks like, `com.android.application` is broken with recent gradle, and something may need work. if so, what would be a replacement for this, and what would be the path to fix it?

please let me know, what other information i should have provided.

thank you for your help

**Comment by wiiaam** [comment]
You should use the included gradle wrapper in the base directory of the project.

First clean any existing project files with `./gradlew clean`

Then build it with `./gradlew build -x link --parallel`

It usually doesn't build the first time successfully so just run `./gradlew build -x link --parallel` again.

Our buildscript uses 
```
./gradlew clean build -x lint --parallel || ./gradlew build -x lint --parallel
```

**Comment by felix-salfelder** [comment]
thanks wiiaam. this might work in some sense, but i am sure there are possible improvements.

`gradlew` runs a binary program that i don't know from the repository (without integrity check?). then, this binary program appears to download some archive supposedly containing gradle-2.10, something I already have up and running. i do not know that i agreed to this download (privacy breach?).

(i cancelled the download. if i trusted random binaries, i could have picked a binary antox apk e.g. from [here](https://pkg.tox.chat/fdroid/repo/antox.apk).)

i would rather like to understand what's going on here... i am used to much simpler build procedures `:|`, but willing to find out what gradle wrapper is meant to do. however, i'm still interested, why plain and  recent gradle is not supposed to work with antox.

**Comment by wiiaam** [comment]
It works the same way as installing gradle through your package manager, but this means that users can build the application without having to temporarily install gradle on their system. 

It also means that by having a specific gradle wrapper being used, we can make sure that the correct version of gradle is being used for building as some versions of gradle may be incompatable (like in your case when you only had 2.10 installed)

Also, gradle doesn't just magically fall from the sky, it needs to be downloaded. By using the gradle wrapper it will automatically download the version of gradle that is used for the project. It does exactly the same thing as installing gradle from a package manager, regardless of what is already installed on the system. If you would prefer to install gradle from source you can A. install gentoo or B. download the source [here](http://gradle.org/gradle-download/)

**Comment by felix-salfelder** [comment]
> It works the same way as installing gradle through your package manager

there's some deep difference here. my package manager only installs what i explicitly want it to install. my package manager downloads from the mirrors that *I* choose. and my package manager (cryptographically) verifies the integrity of the downloaded files.

> (like in your case when you only had 2.10 installed)

this again raises my question, why 2.2 works (does it?) and 2.10 is broken at all. it's bad that an update to 2.10 breaks stuff (maybe that is intended?). then, shouldn't antox move to support the new version? i mean, if there's a new -- say -- android release, will antox not try to support it?

> By using the gradle wrapper it will automatically download the version of gradle that is used for the project.

it started a gradle-2.10 download (i was expecting 2.2?). i understand that if i had gradle-2.2 installed there would be no more need for the wrapper, is that right?

> It does exactly the same thing as installing gradle from a package manager,

it can't. my package manager runs with root privileges. i think it's good that way.

thanks so far.

**Comment by wiiaam** [comment]
We are actually using version 2.8 of gradle right now. You might want to check that you haven't modified the gradle-wrapper.properties file.

Anything that is downloaded by the gradle wrapper would be packaged when you installed gradle through your package manager. If you strongly believe that using a mirror instead of the one used by gradle is is more reliable and secure (it isn't) then you may be able to download an archive from somewhere else. All files are verified to be correct with SHA256.

It can be common that an update of gradle will break certain things as some dependencies can become incompatible. This is why the gradle wrapper is used by almost all android projects.

https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by felix-salfelder** [comment]
>  You might want to check that you haven't modified the gradle-wrapper.properties file.

indeed, i have. somehow it got 2.2 because that's what i was asked to do during my first attempt (probably a bug). (currently trying to get hold of a gradle 2.8).

> If you strongly believe

i don't believe anything yet. i am trying to check. if there's something happening behind the scenes, that is fine. if i cannot know (because it's a binary blob running), then it does not really help.

fwiw: the gradle-wrapper.jar shasum is different from *all* gradle-wrapper.jar's within my andoroid-sdk. does it have to be like that? and i cannot find the place where the mentioned SHA256 checksums are...

> It can be common that an update of gradle will break certain things as some dependencies can become incompatible.

that is not unusual. but rather than working around it, i'd propose to fix it. unfortunately, i cannot figure out what/where `com.android.application` (the thing that complains about gradle) even *is*. maybe it's just too old?

thanks, and sorry for the noise.

**Comment by wiiaam** [comment]
It doesn't shasum the jar, that was already downloaded. It checks the files that are downloaded with the wrapper which can be located at ~/.gradle

Its not just compatibility with Antox that needs to be ensured, its every library included in build.gradle. `com.android.application` is a part of `com.android.tools.build:gradle`, if this is failing then the version of gradle you are using is incompatible.

**Comment by felix-salfelder** [comment]
> It doesn't shasum the jar, that was already downloaded. It checks the files that are downloaded with the wrapper which can be located at ~/.gradle

still, I do not know where the jar file originates from, and i can't find a reason anybody should trust it.
this binary program might even check downloaded files, as you say. now it's hard to really check in practice. see #277 for a more transparent approach to verifying checksums.

besides, I just ran into [this](https://guardianproject.info/2015/04/30/getting-android-tools-into-debian/) article. explains a lot that i did not know about gradle. and indeed there is some work in progress, (which is certainly off topic here). hopefully the wrapper thing will be obsolete some day.

> `com.android.application` is a part of `com.android.tools.build:gradle`

thank you. now that really helped. finally (with other versions of that package) i can see gradle 2.10 working. there is some indication that i should stay with 2.8 (but i am curious). let's see...

**Comment by wiiaam** [comment]
Well all I can say is that if you want to build the application with your own version of gradle, you can go ahead. I haven't really bothered to test an update to 2.10 with the wrapper, since it provides nothing new that I need. If you have any other questions i could suggest asking @optimumtact as he is the build maintainer for Tox and knows a lot about this stuff.

**Comment by felix-salfelder** [comment]
> I haven't really bothered to test an update to 2.10

that's fine. you more or less pointed me to how to approach this `;)`. turns out that i am running into more trouble. a scala compiler (zinc? never heard of it) seems unavailable on my platform, different story.

thanks a lot (and keep going!)
felix

PS: why i do this? on the tox website i read "Everything you do with Tox is encrypted using open-source libraries. The only people who can see your conversations are the people you're talking with.". sure, open-source is fun by itself. but it can only work in the advertised way, if there is a trustable (and reproducible) build process.

**Comment by zoff99** [comment]
@felix-salfelder you can build antox from source but it will take some time
see: https://github.com/zoff99/Antox/tree/zoff99/Antox_v0.25

**Comment by felix-salfelder** [comment]
@zoff99 thanks for advertising your antox fork. please elaborate how it relates to the discussion above. in particular, how did you address verification and reproducibility?
