### ISSUE TITLE
Phone Home Activity.

### ISSUE THREAD

**Issue by gqmrtgma** [Antox/Antox#278]
connect 194.249.212.109:443 HTTP/1.1 <---
connecting to TCP 672 194.249.212.109:h
connecting to TCP 808 178.62.250.138:33
connecting to TCP 860 78.225.128.39:334
connecting to TCP 960 192.210.149.121:3
connecting to TCP 940 195.154.119.113:3
connecting to TCP 1004 205.185.116.116:
connecting to TCP 1104 104.167.101.29:3
connecting to TCP 1184 23.226.230.47:334
connecting to TCP 1156 76.191.23.96:334
connecting to TCP 1204 103.38.216.87:33
connecting to TCP 1220 192.254.75.102:3
connecting to TCP 640 46.38.239.179:334
connecting to TCP 1216 130.133.110.14:3
connecting to TCP 656 212.71.252.109:33
connecting to TCP 604 192.99.168.140:33
connecting to TCP 712 108.61.165.198:3
connecting to TCP 752 178.21.112.187:3
connecting to TCP 728 195.154.109.148:
connecting to TCP 780 80.232.246.79:33
connecting to TCP 724 198.98.51.198:33
connecting to TCP 704 144.76.60.215:33
connecting to TCP 692 192.3.173.88:3344
connect 194.249.212.109:443 HTTP/1.1 <---

**Comment by gqmrtgma** [comment]
Why Antox make a connection to 194.249.212.109:443  when:
1. I opened Antox app
2. I login to my 'INCOGNITO' account
3. I logout my account

Also, what data is leaking by connecting to 194.249.212.109:443?

**Comment by gqmrtgma** [comment]
If you collect Android's GUID or something, I hope you be honest at me.

**Comment by ProMcTagonist** [comment]
Antox is connecting to the Tox network. Antox is an instant messenger, it requires internet.

**Comment by wiiaam** [comment]
This is just the client bootstrapping into the Tox network. You can see that https://nodes.tox.chat/ that 194.249.212.109 is fluke571's bootstrap node
