### ISSUE TITLE
timestamps for recieved messages should reflect time sender sent, rather than reciever recieved

### ISSUE THREAD

**Issue by ghostlands** [Antox/Antox#282]
This would better approximate offline messaging. Currently timestamps make little sense when reviewed in a thread.

Obviously this may require various extra functions (scraping timezone from the OS, adding some kind of header to each message) but there is almost no reason to even have timestamps as things are.

You know quite well when you send messages and most of the time when you receive them - but sometimes I get a message that was sent days ago and Antox stamps it as fresh. IT ISN'T

If this this a protocol issue (seems likely), say so and I'll file an issue over there.

**Comment by wiiaam** [comment]
I don't think that the sender actually sends the time that the message was sent, and if they did, relying on this would be stupid as it would be possible to fake a timestamp

**Comment by zoff99** [comment]
+1
almost every other messeging tool has this. see smssecure as example

**Comment by ghostlands** [comment]
Would it be any easier to fake a timestamp than it would be to fake the message itself? My suggestion was to add timestamp data onto each message. @wiiaam

So I should rephrase part of my issue more directly: is this a protocol issue? Should the Tox protocol add this information automatically to each message? Because unless Tox becomes BitMessage I don't think there ever will be offline messaging, and the best thing to do then is approximate that kind of value as much elsewhere as possible.

**Comment by subliun** [comment]
Yes this is a protocol issue. There were plans to add information about when a message was composed to the protocol (seen in the documentation here https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L1534-L1538), but irungentoo decided against it. There is an [open issue](https://github.com/irungentoo/toxcore/issues/1450) on toxcore to have this feature implemented.

**Comment by ghostlands** [comment]
@subliun That's it exactly. Thanks, and commented.

**Comment by zoff99** [comment]
wow, this is a really big feature missing then.

**Comment by wiiaam** [comment]
The problem is that most messaging tools would connect to a remote server which would verify when the message was sent. The server will add a timestamp to a message and send it to its intended recipient. Because Tox doesn't use servers, instead P2P, you would be relying on the sender actually providing a truthful timestamp

**Comment by ghostlands** [comment]
@wiiaam Now I see what you were thinking of when you said "fake", but I've understood that this process would be dependent on - and subsequently only as reliable as - the system clock of the sender from the beginning.

Most determined encrypted messenger applications/protocols/etc. these days include a blurb somewhere in their online/offline documentation regarding what the are strong against, and what they are not designed to or do not intend to address. In this case publicly stating that timestamps are vulnerable to incorrectly set system clocks due to the nature of the system seems 100% professional.

Considering that the user sending the timestamp would have to be the one doing the faking (or just being stupid), what are we doing trusting content from this person in the first place? And now we're back to the point of messages and timestamps both having the same level of trustworthiness, albeit possibly for slightly differing reasons.

As an interesting side note, running Tox over Tor reduces the likelihood of bad timestamps significantly due to the fact that Tor requires a correctly set clock.

I vaguely remember an encrypted messenger project somewhere railing against relying on correctly set clocks - here we have a nice test case with good arguments for it.

I think we need to either complete this feature, decide that timestamps aren't part of Toxcore, or change the display of timestamps to explicitly use the word "received".

**Comment by GrayHatter** [comment]
@ghostlands I don't think that's needed. Only because there's no reason we can't use timestamps. They're not used in the crypto, nor in messaging, it's just for ease of use.

There's a few good reasons why you'd want a time delta, this is just one of them. Then, once you're aware of surrounding issues/vulnerabilities there's no risk to security.

**Comment by ghostlands** [comment]
@GrayHatter Yeah, currently. But part of my suggestion is to go ahead and make them part of the messages.

And in the case of ease of use, it doesn't really make it easy if the client isn't clear what the timestamps actually mean (or don't). When I literally just answered the ring It isn't really very valuable to see a timestamp, the time is sitting right there in the toolbar millimeters away... I know what time it is. And keeping it there for record keeping purposes is not super useful either, since messages are often cleared to save space on the device, or not kept in the first place for security reasons. The best use of timestamps under these conditions would be to reflect when the sender sent it. Especially because sometimes *the data is time sensitive*...

...non-exotic real world scenarios: I've gotten invitations that I thought were for that day, when in fact the event was over a day prior - it's absurd. One time (not recently) I actually went to a place and no one was there, figured out what happened later.

I guess if people won't budge on this I'll just beg for the easiest fix, which would be the client-GUI addition of the word "received" to the timestamp visual.

**Comment by ghostlands** [comment]
This too though: 

> most messaging tools would connect to a remote server which would verify when the message was sent. The server will add a timestamp to a message and send it to its intended recipient.

So then we're talking about most other messaging clients out there providing unreliable time information, because part of what the Tox project is predicated upon is the weakness of the server link in the chain of trust. This would indicate that unless time information was queried through harcoded means by the local client from a trustworthy timeserver somewhere, timestamps are inherently weak.

Ok, so they just are. But let's not make them confusing and counterintuitive on top of that.

**Comment by wiiaam** [comment]
Closing as protocol issue, which we cannot fix. An issue can be made at the toxcore repo https://github.com/TokTok/c-toxcore
