### ISSUE TITLE
Load profile from qTox

### ISSUE THREAD

**Issue by SergeyDjam** [Antox/Antox#284]
Hello,  i can not load my profile in Antox before exporting from qTox

**Comment by SergeyDjam** [comment]
This problem exists only when there are characters other than alphabet profile file name such as @

**Comment by SergeyDjam** [comment]
normal name file of profile 
name.tox

error name file of profile
na@me.tox

**Comment by wiiaam** [comment]
I'm not a fan of having the @ sign in peoples usernames as they would cause confusion with toxme

**Comment by bngs** [comment]
My .tox file doesnt even show up and the file browser in Antox is really messed up. It only shows certain folders and I cant navigate back to /storage/emulated/0 if I go to /.

**Comment by wiiaam** [comment]
@bngs Currently I have not completed support for android 6 permissions as it requires me to go through and find every instance that the permissions are used and check that they have been granted, which is taking a long time. For now though you will have to enable permissions in settings.

**Comment by darkman088** [comment]
Hey, this is great! Enabling access to storage solved my problem!
But please advise how to transfer my contacts from one phone to another ???
It's of course, not even possible to display to Tox ID of a contact... ???
This is really frustrating :-/
