### ISSUE TITLE
f-droid repo is unsigned, hence installs can be MITMed by party with CA cooperation

### ISSUE THREAD

**Issue by dlmetcalf** [Antox/Antox#296]
The private fdroid repo doesn't have a signature.  It's should, or better yet, should move to using FDroid's main repo and only provide the other as a backup or alpha stream (which I guess is exactly what it's doing now).

Like many users, I won't add a random repo that can impersonate any other app coming from the FDroid repo.  (Nothing personal, but I don't know you).

I'm guessing this is waiting until the app is stable enough for release to fdroid main repo?

**Comment by wiiaam** [comment]
There isn't really much I can do apart from arranging it to be signed, as the repo is run by The Tox Project.

**Comment by ghostlands** [comment]
@wiiaam 

One thing you might be able to do to at least improve the situation is see to it that the builds coming from Jenkins have hashes. As it is, it seems hit or miss whether any given build from Jenkins has a calculated and published hash.

@dlmetcalf 

I know this isn't as good as a signed hash, but it at least would be an incremental improvement.

**Comment by rdarioc** [comment]
Is the repo updated? Google seems to have a more recent version. 

BTW,  it seems like now the repo is signed.  Thank you 

On May 18, 2016, 00:27, William Howell wrote:
There isn't really much I can do apart from arranging it to be signed, as the repo is run by The Tox Project.

**Comment by wiiaam** [comment]
@rdarioc The play store will usually have a more recent version as new updates are pushed as soon as the build is successful, unlike the fdroid repo which is checked nightly for changes

**Comment by physkets** [comment]
> BTW,  it seems like now the repo is signed.  Thank you

I can't seem to find the fingerprint.
