### ISSUE TITLE
TCP relay

### ISSUE THREAD

**Issue by sim6** [Antox/Antox#302]
Firstly, thanks for your work.

Is TCP relay enabled?

Thanks again.

**Comment by wiiaam** [comment]
@sim6 yes it is

**Comment by sim6** [comment]
Please could you add an option to disable the TCP relay on mobile data connection?

**Comment by wiiaam** [comment]
TCP relays reduce the amount of mobile data used though

**Comment by anon8675309** [comment]
"Enable UDP" is now in the Network Settings.  Does this resolve this issue?

**Comment by wiiaam** [comment]
Yeah pretty much, tcp on tox relies completely on tcp relays, theres no way of turning them off
