### ISSUE TITLE
Can't find profile.db history file

### ISSUE THREAD

**Issue by gnouts** [Antox/Antox#303]
I try to export my antox profile to qtox but it only give me a 'profile.tox' and I don't have my history. Is there a database file for history like in qtox?
Also I can't find antox repository in Android.

I use Antox 0.24.381 on Samsung galaxy A3 16 and Android Lollipop 5.1.1.

Thanks and sorry for bad english.

**Comment by wiiaam** [comment]
Currently there is no way to transfer chat history as there is no client spec for it. Each client uses their own methods of storing messages, and whilst qTox and Antox both use sqlite databases, they are incompatible with each other without converting the tables.

**Comment by gnouts** [comment]
Thanks for your answer William.
Is converting the tables something difficult? I don't know anything about database but can't it be done by a script or a little program ?
So where can I access Antox database?

**Comment by wiiaam** [comment]
All the database files are located in the /data/ folder, however accessing this requires root access as it is kept off limits for security reasons. Converting tables is definitely possible, but it takes a while and I don't really have an idea of how the qTox tables are structured
