### ISSUE TITLE
Latest version has default caps

### ISSUE THREAD

**Issue by justa9** [Antox/Antox#309]
Hey! 

It seems that in the latest version of Antox, uppercase letters are automagically selected. Is there a way to turn it off?

**Comment by wiiaam** [comment]
What do you mean by uppercase letters, Abc, where only the first letter is capitalized or, ABC, where everything is capitalized

**Comment by justa9** [comment]
The latter.

**Comment by Grokafar** [comment]
I had the same problem, reinstall Antox solve the problem. You can try to clean the cash.
Before reinstall mind to export your profile ;)

**Comment by justa9** [comment]
Did reinstall with the latest version, however the problem persists.

**Comment by justa9** [comment]
On a second note, the problem seems to have been fixed now.
