### ISSUE TITLE
Disable ToxDNS by default

### ISSUE THREAD

**Issue by ghost** [Antox/Antox#310]
> https://wiki.tox.chat/users/faq
> There are various possibilities like ToxDNS which make the contact easier
> unfortunately at the unavoidable price of lost protection.

The "Incognito" mode should be the default on registration page.
Also, please add a checkbox to "(_) Register to ToxDNS. 'What?(link)'" which is off by default.

Privacy-by-design is important.

**Comment by wiiaam** [comment]
I'm sure I suggested this to @subliun a few hundred times so I guess it might be time to change it around
