### ISSUE TITLE
Stop Antox botnet from DDoS'ing poor guy Jenkins

### ISSUE THREAD

**Issue by nurupo** [Antox/Antox#311]
Could you make Antox access [the nodefile on Jenkins](https://github.com/Antox/Antox/blob/08e47ed1254fa5a220ae837c235e334257b29653/app/src/main/scala/chat/tox/antox/tox/ToxSingleton.scala#L72) less frequently? We get so many hits from Antox users that it's not even funny.

```sh
$ wc -l access.log
223632 access.log
$ grep -c Nodefile access.log
183672
```

So, ~82% of all web requests made to build.tox.chat are requests for `job/nodefile_build_linux_x86_64_release/lastSuccessfulBuild/artifact/Nodefile
.json`

Also, that `access.log` is a log for 2 days only. There are 183672 requests for the nodefile in 2 days and only 172800 seconds in 2 days, meaning that on average we get more that 1 request for Nodes file per second.

**Comment by wiiaam** [comment]
I find this funny

**Comment by nurupo** [comment]
Well, at least now we know why @stqism had 6 load balancing servers.

**Comment by nurupo** [comment]
I suggest using a list of hardcoded nodes and access the nodes file on Jenkins only when you can't connect to the DHT with hardcoded nodes, and even then, cache the nodes file on the device for a week or something.

**Comment by wiiaam** [comment]
@nurupo caching is so 2010, everything is in the :cloud: these days

**Comment by GrayHatter** [comment]
keep the antox bot net pls!!

**Comment by nurupo** [comment]
The stats in the opening post are from ~2 weeks ago.

Current stats

```sh
$ wc -l access.log
355776 access.log
$ grep -c 'Nodefile.*Android' access.log
325890
```

325890/355776 = ~0.916, so that's ~91.6% of all accesses.

That log file is from Jul 3 06:25 to Jul 6 03:22. [There are 248220 seconds in that interval](https://www.wolframalpha.com/input/?i=seconds+between+Jul+3+06:25+and+Jul+6+03:22), vs 325890 requests.

**Comment by cebe** [comment]
just curious, why do you get the nodes from the build server instead of https://nodes.tox.chat/ ?

**Comment by nurupo** [comment]
@wiiaam has asked me to count unique users. I have counted unique users by the combination of <ip> and <useragent> (e.g. `255.255.255.255 Dalvik/1.2.3 (Linux; U; Android 1.2.3; D1234Build/12.3.A.4.567)`)

```sh
grep 'Nodefile.*Android' access.log | awk '{ print $1$12$13$14$15$16$17$18$19$20$21$22 }' | uniq sorted.log | wc -l
34599
```

**Comment by wiiaam** [comment]
@cebe nobody could be bothered to change the json parsing

**Comment by cebe** [comment]
> @cebe nobody could be bothered to change the json parsing

swap `servers` to `nodes` [here](https://github.com/Antox/Antox/blob/08e47ed1254fa5a220ae837c235e334257b29653/app/src/main/scala/chat/tox/antox/tox/ToxSingleton.scala#L104) and `pubkey` to `public_key` [here](
https://github.com/Antox/Antox/blob/08e47ed1254fa5a220ae837c235e334257b29653/app/src/main/scala/chat/tox/antox/tox/ToxSingleton.scala#L111) and you are done...

**Comment by wiiaam** [comment]
Well I've got the day off tomorrow so I guess I'll fix it. @nurupo have you checked to see if any of the other clients are accessing it?

**Comment by nurupo** [comment]
@wiiaam See https://github.com/Antox/Antox/issues/311#issuecomment-230698215 . There are total of 355776 accesses to everything at Jenkins, and 91.6% of them, 325890 of them, are from Android devices to the Nodefile specifically.

**Comment by nurupo** [comment]
@wiiaam here

```sh
$ cp access.log access.log-copy
$ grep -c 'Nodefile.*Android' access.log-copy
396968
$ grep -c 'Nodefile' access.log-copy
396972
```

There were just 4 accesses to the file from non-Android device during 3.5 days.

**Comment by GrayHatter** [comment]
3 of them were likely @nurupo checking to see what the file was, the 4th was @cebe

**Comment by stqism** [comment]
> Well, at least now we know why @stqism had 6 cnd servers.

If theres anything I was realy great at, infrastructure was it. 1 request a second is hardly a lot, so why not use cloudflare with strong caching?

**Comment by GrayHatter** [comment]
@stqism nah, you're better at stealing money from Tox

**Comment by wiiaam** [comment]
@nurupo 
>3.5 days

Are the servers running GTX 970s?

**Comment by nurupo** [comment]
No, it's just that the log file rotates every few days due to it becoming too large, which is not surprising given all these accesses from Antox users.

Didn't get the GTX 970s humor.

**Comment by wiiaam** [comment]
@nurupo it should be caching now, give it a few days for clients to update and have a look at the access logs.

**Comment by optimumtact** [comment]
@nurupo the gtx970 was advertised as a 4g card but the last .5 was slow memory, so it became a big blowup about the card that had 3.5g

**Comment by rdarioc** [comment]
Is Fdroid build still maintained? 

On July 8, 2016, 14:42, William Howell wrote:
@nurupo it should be caching now, give it a few days for clients to update and have a look at the access logs.

**Comment by wiiaam** [comment]
@rdarioc hmm the fdroid doesnt seem to be updating

**Comment by optimumtact** [comment]
There was a configuration bug in the fdroid updater, it should now be resolved

**Comment by rdarioc** [comment]
Thanks for fixing it. 

---
R. D. Contarino


On July 11, 2016, 07:14, oranges wrote:
There was a configuration bug in the fdroid updater, it should now be resolved

**Comment by nurupo** [comment]
@wiiaam cool, looks like it's decreasing

```sh
$ cp access.log access.log-copy
$ grep -c 'Nodefile.*Android' access.log-copy
291522
$ grep -c 'Nodefile' access.log-copy
291522
$ ls -lbh
-rw-r----- 1 www-data adm   84M Aug  7 07:48 access.log
-rw-r----- 1 www-data adm   73M Jul 31 06:25 access.log.1
...
```

We are getting a little more than 1/3 of hits we were getting before in https://github.com/Antox/Antox/issues/311#issuecomment-230895669.
