### ISSUE TITLE
Various bugs on Marshmellow 6.0.1

### ISSUE THREAD

**Issue by JFreegman** [Antox/Antox#313]
I just tried out Antox from the play store for the first time since I upgraded to Marshmellow 6.0.1. I'm not sure if the upgrade caused these bugs or if there was a regression in the code base:
- audio calls are broken (can only receive audio, not send)
- camera button does nothing
- video button starts an audio call but doesn't start video. Does nothing when in a call.
- nothing happens after i select an image to send 
- keyboard defaults to capslock on

**Comment by zoff99** [comment]
it works for me on 6.0.1

**Comment by wiiaam** [comment]
@JFreegman can you post your device/os, I've been getting reports of stuff like this but it's fine on my Android 6 emulator

**Comment by 0mark** [comment]
I have the same problems (except the caps lock, but plus: file selection for upload shows every directory as empty, except the root directory)
Device is Galaxy s5. OS is Cyanogenmod 13.0 (20160726 nightly). I use microG as google play services replacement (i dont think thats importent in this case, but eh, one never knows)

**Comment by NishaYume** [comment]
Im android 6.0 with umi super phone. And i can accept call and hear the voice but caller dont hear me. File selection show empty. Photo button dont work too. Crash when i try to put avatar,with file and trying photo.
I like antox. Hope this help to you. Sorry for me english

**Comment by macandchief** [comment]
If the caller cannot hear you, make sure the microphone permission is set correctly. I'm on Beanstalk 6.0, so basically CM 13 and it crashes immediately if someone calls me with a win uTox client. I can make a call to that client and it works.
