### ISSUE TITLE
Antox 0.4.421 can't be installed to Android 5.1

### ISSUE THREAD

**Issue by TotalCaesar659** [Antox/Antox#319]
Antox 0.4.421 can't be installed to Android 5.1 (Cyanogenmod 12.1). Version 0.24.383 can be installed normally.
![1](https://cloud.githubusercontent.com/assets/14265316/17062806/21b331fc-503d-11e6-8375-ff0361494400.png)
![2](https://cloud.githubusercontent.com/assets/14265316/17062831/36140e0a-503d-11e6-8c48-0aa35f69937f.png)
![3](https://cloud.githubusercontent.com/assets/14265316/17062839/3b2aebe8-503d-11e6-90cb-4c794f3c92b3.png)

**Comment by savegame** [comment]
In my CyanogenMod 12.1 it install normally ?but can't login #318

**Comment by TotalCaesar659** [comment]
I've forgot to say: my version is from official site (https://build.tox.chat/job/antox_build_android_arm_release/lastSuccessfulBuild/artifact/antox.apk).

**Comment by wiiaam** [comment]
@TotalCaesar659 that apk is no longer being signed so it probably wont work anymore unless you sign it yourself, if you want a signed apk you can download one for now from the fdroid repo: https://pkg.tox.chat/fdroid/repo/antox.apk

**Comment by nurupo** [comment]
@wiiaam should we change the APK link on our website to point to APK from fdroid repo on pkg.tox.chat?

**Comment by wiiaam** [comment]
yes

**Comment by nurupo** [comment]
Wow, you could have told us of the issue earlier.
