### ISSUE TITLE
F-Droid repo package category

### ISSUE THREAD

**Issue by licaon-kter** [Antox/Antox#331]
Now it's setup as "None", can it be changed to "Internet" maybe?

Reference: https://gitlab.com/fdroid/fdroidclient/merge_requests/388

**Comment by wiiaam** [comment]
You will need to talk to someone like @nurupo or @optimumtact to sort this as the Tox Foundation maintains the F-Droid repo

**Comment by licaon-kter** [comment]
Hopefully they just got pinged. Thanks

**Comment by nurupo** [comment]
@licaon-kter just set the category to "Internet", thanks for pointing this out.
