### ISSUE TITLE
Cannot export profile

### ISSUE THREAD

**Issue by Kondra007** [Antox/Antox#337]
Hi there. Running Antox 0.24.422 on Android 6.0.1. Device: Oneplus One.

The problem is: when I press "Export profile", dialog window appears with `/storage/emulated/0` directory empty. What is worse, when I reach `/` and then enter `/storage` again, it appears empty! 
There's no `/sdcard` or `/mnt/sdcard` visible, so I can't reach my sdcard in any way. (Of course, there **are** `/sdcard` and `/mnt/sdcard` if browing via any other file manager).

**Comment by licaon-kter** [comment]
Settings->Apps->Antox->Permissions->Storage is ON?

**Comment by Kondra007** [comment]
@licaon-kter ah, okay, that was off by default. That's strange that app didn't ask for permission though.
