### ISSUE TITLE
Is Antox, and tox in general, really that anonymous and secure?

### ISSUE THREAD

**Issue by selfmade-exe** [Antox/Antox#347]
Hello everyone. After reading about how decentralized tox is in this thread
https://github.com/irungentoo/toxcore/issues/1398
and witnessing the censor of the guy that rightfully raised these concerns,
I checked the antox connections, and here is my firewall log on my android running antox:
![log](https://cloud.githubusercontent.com/assets/21176256/18890233/2853c9e8-84b5-11e6-8282-2a7a0320cd49.png)

WHAT THE F* are those links? And on top of it all, GOOGLE.COM (about in the middle of the log)
Someone plz explain all these; why I (and everyone else) that want to use any tox client, for sequrity and anonymity, have to do with all those severs, and in particular, google???

Edit: I forgot to mention that this log was generated as I just opened the antox, just for a few secs..

**Comment by cebe** [comment]
All those links exist because Tox is decentralized, that means it does not connect to one server but many nodes in the network.

The google.com is just someone who set the reverse record for his IP to google.com for fun, the IP itself belongs to some russian network company:

```
$ whois 193.124.186.205
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '193.124.184.0 - 193.124.191.255'

% Abuse contact for '193.124.184.0 - 193.124.191.255' is 'abuse@marosnet.ru'

inetnum:        193.124.184.0 - 193.124.191.255
netname:        MAROSNET-193-124-184-0
descr:          Marosnet enterprise network
geoloc:         55.755768 37.617671
country:        RU
admin-c:        MRS1
tech-c:         MRS1
status:         ASSIGNED PA
mnt-by:         MAROSNET-MNT
created:        2016-02-01T20:25:30Z
last-modified:  2016-02-01T20:25:30Z
source:         RIPE

role:           MAROSNET TC LLC NOC
address:        MAROSNET Telecommunication Company
address:        office 516,17, Lobachika St.
address:        107113
address:        Moscow
address:        Russian Federation
phone:          +7 499 2645777
fax-no:         +7 499 2645344
remarks:        trouble: ------------------------------------------------------
remarks:        trouble: About any problems please contact us
remarks:        trouble: ------------------------------------------------------
remarks:        trouble: Routing and peering issues: noc@marosnet.ru
remarks:        trouble: SPAM issues: abuse@marosnet.ru
remarks:        trouble: Network security issues: noc@marosnet.ru
remarks:        trouble: General information: provider@marosnet.ru
remarks:        trouble: ------------------------------------------------------
admin-c:        VANL1-RIPE
tech-c:         MAX177-RIPE
nic-hdl:        MRS1
mnt-by:         MAROSNET-MNT
created:        2014-05-26T14:00:50Z
last-modified:  2015-03-13T08:14:17Z
source:         RIPE # Filtered

% Information related to '193.124.176.0/20AS48666'

route:          193.124.176.0/20
descr:          MAROSNET Telecommunication Company Network
descr:          Moscow, Russia
descr:          http://www.marosnet.ru/
origin:         AS48666
mnt-by:         MAROSNET-MNT
created:        2015-12-08T13:20:19Z
last-modified:  2015-12-08T13:20:19Z
source:         RIPE

% This query was served by the RIPE Database Query Service version 1.87.4 (DB-2)
```

**Comment by ALPhaKiLLer** [comment]
Yep, just as cebe said. Tox doesn't have one central connection point, rather it has many nodes it connects to.

**Comment by selfmade-exe** [comment]
Of course I know that tox is supposedly decentralized (toxcore thead #1398), and ok that google.com isn't google.com but still google collects data, but why most of the servers are corporate (belong to companies/corporations), like rev.cloud.scaleway (8th from the last in th log) or deadteam.net?? If tox is to be decentralized & free & secure & anonymous, and made by-its-users, why have data traffic through companies?? Plz correct me if I am wrong in something or have misunderstand.

**Comment by cebe** [comment]
there is no traffic "through" companies, there is traffic between nodes of the tox network. Traffic for looking up friend nodes (to see who is online in your contact list) is going through the distributed hash table (foreign nodes).
If you send messages, they are directly sent between you and your communication partners computer, there is no 3rd party involved.

> rev.cloud.scaleway (8th from the last in th log) or deadteam.net

what makes you think these are companies? They are just domain names registered by some persons which are set up as [reverse lookup addresses](https://en.wikipedia.org/wiki/Reverse_DNS_lookup#IPv4_reverse_resolution) for the IPs you connected to.

**Comment by ALPhaKiLLer** [comment]
I'm pretty sure the Tox nodes list wouldn't include actual companies.

**Comment by zoff99** [comment]
i guess this would be people using tox at those places, or just nodes running tox on a shared hoster.
but it doesn't matter, since its all encrypted traffic.

**Comment by ProMcTagonist** [comment]
unless you manage to fling your packets through the air from your device to your friend's, they have to travel through super scary companies like your internet service provider

**Comment by licaon-kter** [comment]
Wasn't this encrypted? How would you know what country (Russia) the users live in and what do they share/talk (anime) ?

**Comment by ameenross** [comment]
Can't IP addresses be geolocated....

**Comment by rdarioc** [comment]
@ameenross , of course IP addresses can be geo-located (with some approximation). But this is the usual confusion between anonymity and secrecy (of the exchanged correspondence). TOX provides secrecy of the exchanged correspondence. It only gives you "little" anonymity, in the sense that it doesn't ask you to sign a contract where you are forced to declare your name. That doesn't mean that someone looking at the IP addresses may not think that the same Telco subscriber using such IP address at certain time, is the same user who is using Tox, at the very same time. That, of course, assuming that the Telco provider is "willing" to give out your ID on request. Extra level of anonymity can be added using VPNs or distributed network services such as I2P (I am not mentioning Tor purposely). Anonymity is a completely different matter and has nothing to do with Tox.

**Comment by selfmade-exe** [comment]
> there is no traffic "through" companies, there is traffic between nodes of the tox network. Traffic for looking up friend nodes (to see who is online in your contact list) is going through the distributed hash table (foreign nodes).
If you send messages, they are directly sent between you and your communication partners computer, there is no 3rd party involved

**Comment by selfmade-exe** [comment]
My bad for closing/reopening

Can someone plz give a short description/senario about whats going on when antox starts and what happens prior and when two nodes are communicating?

**Comment by subliun** [comment]
You can find information about how Tox works on the [Tox wiki](https://wiki.tox.chat/).
