### ISSUE TITLE
Unable to add the user through entering the ToxID: it says "Invalid ToxID"

### ISSUE THREAD

**Issue by yurivict** [Antox/Antox#349]
I first copied and pasted it from the message. Then typed it manually - same result.

This is a major problem, no workaround.

**Comment by ALPhaKiLLer** [comment]
Just to be sure, you are copying the hex ID, and not a ToxMe ID, right?

**Comment by yurivict** [comment]
I am copying the public key, the only thing qTox displays. Now I realize that pubkey < ToxID. However, it is possible to add user using only the pubkey. This raises the confusion as to why pubkey can't be used. I think this is a general tox problem.

**Comment by ALPhaKiLLer** [comment]
I haven't contributed to Antox code-wise (yet) so I can't say what is causing this/how to fix it, perhaps an Antox developer can help you with that.

Do other Tox programs you use have this problem?

**Comment by archnous** [comment]
I'm having the same issue, using the toxme.io ID. I'm getting the 'Invalid Tox ID' error, and so is my contact. We're both on kitkat; a third friend on 5.1 can add us using our toxme IDs without problem.

**Comment by yurivict** [comment]
This looks like the general tox problem. PubKey<ToxID. Both they look similar, and both can be used to add contacts, but Tox officially only supports ToxID.

**Comment by ProMcTagonist** [comment]
>both can be used to add contacts

Adding with public keys require each contact to add the other. Tox IDs send friend requests.

**Comment by wiiaam** [comment]
Tox IDs are public keys with a nospam added. The nospam can be changed at the users discretion to get a new unique Tox ID if they are being flooded with friend requests. You cannot add someone without also having their current nospam.

**Comment by yurivict** [comment]
Ok, thanks. I think many people will be confused because of this though.
