### ISSUE TITLE
Im New Her - Any Help !

### ISSUE THREAD

**Issue by Nemra1** [Antox/Antox#356]
hello antox Users..im new her and i want to know some information about this project
# in the paste i wass used 123flashchat but this script dosnt support mobile ..what ever

i want to know if Antox have admin panel or user level or public chat room with member level like

**Comment by aaannndddyyy** [comment]
Hello @Nemra1 .
Antox does not have such a feature yet.
But it is in the works. Mening that tox will in the future have public chats with moderators and one owner (super admin/mod) per group.

**Comment by wiiaam** [comment]
Currently these sort of features do not exist but there are plans for adding things like this

Antox is only a client for [toxcore](https://github.com/irungentoo/toxcore), any feature requests can be made there
