### ISSUE TITLE
change default screen to last activity

### ISSUE THREAD

**Issue by aaannndddyyy** [Antox/Antox#359]
I don't know what you call them, but IMHO the default screen should not show the contacts listed alphabetically but rather the other one, to the left, where chats are sorted according to most recent activity. This way saves time and is more easily accessible.

**Comment by Beast141** [comment]
yes im having the same issue here.
When messaging a user and then clicking back, by default the screen goes to the contacts list instead of the message list. I have to manually click the message list to go there.

**Comment by wiiaam** [comment]
Yeah that's probably a good idea

**Comment by wiiaam** [comment]
It will always go to the one that you last had open, so if you opened a message through contacts, and press back, it will return to contacts. Same with recent. Now though, when you login it will default to the recent tab instead of contacts unless there are no recent messages.

**Comment by aaannndddyyy** [comment]
That's good news. thanks.
However, maybe it should always default to recent, not only if there are unread messages.
Why?
Becasue recent keeps track of the ones you have chatted with most recently.
Maybe your contacts under A are the ones you harldy chat with, but the ones you most often chat with are Sarah and Tom. Even if there are no unread messages from those contacts, it's most likely that the next message you will wanna send, will be for one of them, so it makes sense to have them readily available at the top, instead of scrolling down needlessly.
