### ISSUE TITLE
Antox often crashes after internet connection was interrupted

### ISSUE THREAD

**Issue by aaannndddyyy** [Antox/Antox#361]
this is a very high priority for me

**Comment by licaon-kter** [comment]
Clearnet or Tor?

**Comment by aaannndddyyy** [comment]
Am using tor, but in wifi only, mode. and when wifi goes away, or sometimes when phone just goes to standby, when I come back, Antox is empty (no contacts) and shortly after crashes, or it immediately crashes as soon as I enter it again.
"Antox stopped working and will be terminated".
Sometimes that happens twice, i.e. ass soon as it was terminated and I open it again, it immediately terminates a second time. 
After that, I can open it just fine. 

I don't know if this affects only proxified mode, since I do not ever use it without.

**Comment by licaon-kter** [comment]
Do try to get a log of the crash, if you have root use aLogCat if not try with ADB and a PC.

**Comment by zoff99** [comment]
can you try with the latest development version:
https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25.1

after a crash the crashlog will be saved to SD Card.
