### ISSUE TITLE
Annoying problems with Android 6.0

### ISSUE THREAD

**Issue by darkman088** [Antox/Antox#364]
Hello,

I have a new phone and a lot of new problems. Unfortunately - Antox is among them.
I figured out, that as soon as I switch to another app, I am being logged off from Antox.
Also, during voice calls, if the screen goes off, I stop hearing my counterpart and my
counterpart can't hear me either.
Please take care of these bugs, when releasing the next version.

Many thanks in advance!

**Comment by licaon-kter** [comment]
Device? Android version? Logs?

**Comment by darkman088** [comment]
Yeah, sorry, pretty lame from my side :-/
Samsung Galaxy Note 3, Android 6 (custom ROM - artas182x).
Logs - no idea what do you need and how can I collect it.

Thanks for your attention!

**Comment by licaon-kter** [comment]
aCatLog or ADB via PC or Termux->`su`->`logcat -v threadtime >/sdcard/log1.txt`

**Comment by wiiaam** [comment]
It could be that your background app count has been lowered, you can change this in developer settings

![screenshot](https://sr.ht/FqIv.png)

**Comment by zoff99** [comment]
it's android 6.0 it sometimes puts the app to sleep. try to disable all battery optimizations in your ROM settings

**Comment by zoff99** [comment]
have you tried the latest development version?
0.25.1
