### ISSUE TITLE
Receiving photos stops receiving!!

### ISSUE THREAD

**Issue by 2SI3NX** [Antox/Antox#366]
when i receive photos from another user, i accept and see that i am busy receiving it in the progress bar.. but at some point it stops. it shows speed sometimes but sometimes when i receive it doesnt.
I have to tell the user to resend another 2 times, 3rd times the charm i finally receive it.

Also the speed goes from 1kbps to 19 or 20kbps. and drops low. thats when it stops receiving.

Can you set this that the receiving doesnt time out after network disconnection or something? or that it will carry on sending till its received?

Can you tell me how the offline feature works? if the user goes offline while im busy receiving a message or photo, will it stop on my side? does the user have to be online for me to fully receive the photo or message?

Also sometimes messages dont deliver and i have to resend them.

**Comment by licaon-kter** [comment]
Device? Android version?  App version? App source? Server? Tor? Wat?

**Comment by Beast141** [comment]
Sorry i forgot.
Sony Xperia Z5 E6683.
Android 6.0.1
Fdroid Version - latest version.
no Tor connection.

**Comment by licaon-kter** [comment]
Server? Or at least list server capabilities... the issue template is here for a reason.

**Comment by Beast141** [comment]
um what template? i cannot see any template when opening an issue on here.
How do i see what servers Antox connects to?

**Comment by licaon-kter** [comment]
Oh, my bad, got things mixed up. :)
