### ISSUE TITLE
Google Play refuses to publish Antox with downgraded SDK requirement

### ISSUE THREAD

**Issue by nurupo** [Antox/Antox#373]
Antox is not getting updated on Google Play anymore due to lowering the required SDK from 23 to 22 in recent commits. Here is an error message from Google Play that we get when publishing it:

>Devices with version 15422 of this app target SDK 23 and would be upgraded to version 15424 which targets SDK 22. This is forbidden as you cannot upgrade away from M permissions.

(Antox on F-Droid did get updated,)

**Comment by licaon-kter** [comment]
Why the lowering?

**Comment by nurupo** [comment]
>Roll back target sdk to fix permission issues

https://github.com/Antox/Antox/commit/74c15352be006c909f5b8c4022ca671442656c0f

Probably related to https://github.com/Antox/Antox/commit/226cb5408dd1e7fd1dd63b3c33dce563ac42d740.

**Comment by licaon-kter** [comment]
Oh, ok, so it needs proper permission triggering, the SDK version change is just a copout until that's fixed.

**Comment by wiiaam** [comment]
"fixed" https://github.com/Antox/Antox/commit/c9fd4402d83f82c17e319aa498abfef151f374b1

**Comment by zoff99** [comment]
also can not update antox on f-droid now. device does not allow to install because of this issue
