### ISSUE TITLE
Cannot import profile because no files show up after click IMPORT PROFILE

### ISSUE THREAD

**Issue by cnzhx** [Antox/Antox#378]
I am using Android 6 on Nexus 5. After clicking the IMPORT PROFILE button, a dialogue shows only `..` in the list under `/storage/emulated/0` but no file shows up so that I cannot choose my profile file. This phone has recently been reset to factory so it's pretty "new". I cannot think about any factor caused this.

I tried the import function on another phone running Android 7.0.1 on Pixel, it has no problem to show the file list.

Any comments?

**Comment by licaon-kter** [comment]
Did you check if the app has Permission->Storage granted?

**Comment by cnzhx** [comment]
@licaon-kter Thanks a lot! You are right. I have not granted the permission. I assumed it would ask for permission if necessary. OMG, what a noob I am.

**Comment by licaon-kter** [comment]
Yes, the app does not yet handle permissions requests on Android >=6, so the user needs to grant them manually.
