### ISSUE TITLE
Tox ID should accept lowercase hex digits

### ISSUE THREAD

**Issue by hans-adler** [Antox/Antox#388]
... not just because this is what almost every other protocol that uses hex digits in some way does. It's also incredibly annoying after entering a Tox ID _manually_ (yes, I just did that), when you used lower case so you at least don't have to press Shift on the on-screen keyboard before each letter, you find that the ID is not accepted and you have to re-write every single letter.

(While I'm here: It would be good to tell new users what the profile name that you ask for in the beginning is used for. I thought it was the human-readable name for the central registry, which I don't want to use. After a lot of fruitless research I finally entered 'a' under the assumption that I would be told this name is already taken. At that point it became clear that this is actually just a local file name or something like that. But this really doesn't go without saying, even though the name 'profile' admittedl7 suggests this purpose. Too many other projects use standard terminology in totally non-standard ways.)

**Comment by hans-adler** [comment]
There was already a partial discussion of this problem in #219, though there it was mostly from the point of view of scanning QR codes. (In my opinion also with very good arguments for converting to upper case.)

Note that the (very valid) criticism of Postel's principle ("be conservative in what you do, be liberal in what you accept from others") doesn't really apply here because the equivalence of upper and lower case hex digits is already a very well established standard in most other domains and the overhead involved in uppercasing is minimal in every respect. The Principle of Least Surprise also seems very relevant to me here. (I certainly was surprised myself.)

**Comment by anon8675309** [comment]
I fixed this and submitted a pull request.
