### ISSUE TITLE
Antox not booting up on Cyanogenmod

### ISSUE THREAD

**Issue by JustAskin** [Antox/Antox#389]
I'm reporting a small bug under CyanogenMod 13. Despite Antox being set to boot on startup, with permission from Privacy Guard, and with Privacy Guard's "Bootup List" actually logging it had started at the current boot among other startup apps, Antox doesn't run in the background until I open it manually.

If PG's log is accurate it would mean that Antox does boot up but immediately shuts down before the ROM's interface is ready. The problem may exist in Android as well since other apps boot normally under CyanogenMod but I can't verify.

**Comment by Zer0-One** [comment]
CyanogenMod has been discontinued, so I'm not sure Antox should be supporting it anymore. We should see if the bug exists in LineageOS once they start putting out builds.

**Comment by JustAskin** [comment]
CyanogenMod (supposedly) has tens of millions of users and Lineage would be based on it anyway. That said someone needs to verify the bug is CM specific and isn't on stock android as well.

**Comment by anon8675309** [comment]
Start on boot does not work on the three devices I have (all running stock Android):
Samsung Tab A ; Android 6.0.1 ; the latest version of Antox as of today (compiled from source)
Nexux 6P ; Android 7.1.1 ; Antox 0.25.456 (15456)
Moto G (3rd Gen) ; Android 5.1.1 ; Antox 0.25.456 (15456)

I do not have any insight as to why this is not working as expected.  If anyone has advice on how I can collect more info on why this isn't working, I'm willing to continue helping to troubleshoot it.

**Comment by wiiaam** [comment]
Start on boot never worked properly in the first place, there were too many issues regarding permissions iirc
