### ISSUE TITLE
Automatically accept incoming file transfers

### ISSUE THREAD

**Issue by palikacska** [Antox/Antox#394]
All file transfers (including pasted images) have to be accepted first before they can be downloaded from the sender. Well, this makes it a bit difficult when I'm away but I still want to receive image or other kind of file attachments, just like messages. Another disadvantage is that the sender has to be online as long as I accept their file transfer request.

I checked the options pane of Antox and found no option for accepting file transfers automatically. I think this would be a **really important and vital feature**  and I don't think it would require a lot of coding.

**Comment by zoff99** [comment]
@palikacska the option is already there in the newest development version v0.25
you can try it here:
https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25

!!careful this is still in development, use at your own risk!!

**Comment by toxtox** [comment]
@zoff99 Yes, this is a really useful feature. In my point of view, this feature would be even more useful in combination with an "**offline messaging for FILES feature**". 
If you try to send a file when you or your friend is offline you get an error telling you something like _**"sending failed - file cannot be sent to an disconnected contact"**_

**Is there a technical reason why offline messaging is not offered for files yet (in contrast to normal text messages)?**

By the way, sending pictures fails, if "_**Strip EXIF data from images**_" is enabled. The picture seems to be completely transfered but does not show up on the receiving device.

**Comment by zoff99** [comment]
@toxtox can you post a screenshot how the picture filetransfer looks on both devices?

**Comment by toxtox** [comment]
@zoff99 
 if "**_Strip EXIF data from images_**" is enabled in Antox v0.25. The picture seems to be completely transfered but does not show up on the receiving device as you can see on the following screenshot:
[http://imgur.com/a/95Ig7](url)

**Comment by zoff99** [comment]
strip exif data is done "in memory" so there could be a bug now.
it does work without strip exif, yes?

**Comment by zoff99** [comment]
@toxtox does it work with "strip EXIF" enabled in the current f-droid/playstore version?

**Comment by toxtox** [comment]
@zoff99 I have not checked this bug with the latest f-droid/playstore version. Could be affected, too. I will check this tomorrow.
Could you reproduce/confirm this bug on your device with Antox v0.25?

**Comment by toxtox** [comment]
@zoff99 I am very sorry, the failing function **_"Strip EXIF data from images"_** it works fine now with your Antox v0.25. Obviously the reason was that I disallowed "**exec**"-commands by the _**Xprivacy**_-module of the **_xposed_** framework for the Antox-app. After allowing exec-commands for Antox the **_"Strip EXIF data from images"_** function and sending pictures were working fine.

**Comment by zoff99** [comment]
great

**Comment by wiiaam** [comment]
Feature added in @zoff99 's PR, discussion about offline files can be made [here](https://github.com/Antox/Antox/issues/397)
