### ISSUE TITLE
[Regression] cannot enter ip for proxy or custom node

### ISSUE THREAD

**Issue by nnnn20430** [Antox/Antox#398]
The input field for proxy address or custom node address only allows one dot to be entered.
I suspect this  is because of this commit:
[cb575211899ec02af315460ab7d9989fcbaa5aba](https://github.com/Antox/Antox/commit/cb575211899ec02af315460ab7d9989fcbaa5aba)

it sets the input to be "decimal" and android probably assumes that a decimal number can have only one dot, an IPv4 address has has 3.
this also doesn't let you enter an IPv6 address or a domain, since the input keyboard on android only gives you numbers and 4 extra symbols, while an IPv6 address requires a ":" and "abcdef" .

my android version is: 6.0.1 (CM13)
Antox version: 0.24.428 (from f-droid repo)

**Comment by wiiaam** [comment]
Changed now
