### ISSUE TITLE
Groups!!

### ISSUE THREAD

**Issue by ProgrammerNinja** [Antox/Antox#401]
Hey team!! Please !! When is the group creation going to be possible please!!

**Comment by ProgrammerNinja** [comment]
@zoff99 Please!! Add groups!!

**Comment by zoff99** [comment]
@ProgrammerNinja do you have scala programming skills?

**Comment by ProgrammerNinja** [comment]
Nope! If you know then can you please the code? Please! That would be awesome of you

**Comment by ProgrammerNinja** [comment]
@zoeff99 Please Help

**Comment by ProgrammerNinja** [comment]
@zoff99 Can please reply? Hmm..!!

**Comment by wiiaam** [comment]
@ProgrammerNinja currently we are waiting for changes to the tox library we use, which is waiting for new groupchats to be added to toxcore

**Comment by ProgrammerNinja** [comment]
@wiiaam How much wait ?? It's been years!! Can approximately tell me how much more time will it take?

**Comment by zoff99** [comment]
@ProgrammerNinja it will take a long time

**Comment by wiiaam** [comment]
@ProgrammerNinja you'll have to check in with the Tox devs to find out that one
