### ISSUE TITLE
jenkins build fails install with no dev key

### ISSUE THREAD

**Issue by sarnold** [Antox/Antox#402]
I typically don't touch android builds (except when someone who pays me asks me to) but I can remember deploying dev builds from jenkins signed with a dev key for CI/testing, etc.  The current antox "latestbuild" on Jenkins fails adb install with:

```
$ adb install ~/Downloads/antox.apk 
3820 KB/s (9854279 bytes in 2.519s)
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl604680472.tmp/base.apk: Attempt to get length of null array]
```

**Comment by sarnold** [comment]
If I could add a label I would call this a Blocker.

**Comment by zoff99** [comment]
rather try the latest development version 0.25.1
https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25

#400

**Comment by gerroon** [comment]
@zoff99 

Is this a legit build or one with a backdoor or something?

**Comment by wiiaam** [comment]
@sarnold @gerroon The lastest version of the signed APK can be obtained from the FDroid repo [here](https://pkg.tox.chat/fdroid/repo/)
