### ISSUE TITLE
Please add instructions how to install the latest dev apk

### ISSUE THREAD

**Issue by yurivict** [Antox/Antox#405]
Please add the link to apk. I needed to try the latest version, and there is no link anywhere. Google Play only has one stable version.

**Comment by zoff99** [comment]
it should be on f-droid antox repo. or you can try the CI build
https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25.1

!! this is a development version !!

**Comment by zoff99** [comment]
i will try to get an official development version or nightly thingy setup

**Comment by yurivict** [comment]
Pulse doesn't work for me either, ```--ao=pulse --audio-device=pulse/oss_output.dsp2``` doesn't play anything. ```paplay --device=oss_output.dsp2 ~/wweed.wav``` plays sound okay.

**Comment by wiiaam** [comment]
The current version of Antox (Google Play and FDroid) is nightly only. Currently we are not releasing stable versions. The latest APK can be found here --> https://pkg.tox.chat/fdroid/repo/antox.apk

**Comment by wiiaam** [comment]
Note that this is also linked on the readme https://github.com/Antox/Antox#getting-antox
