### ISSUE TITLE
Please release 0.25 into google play because it fixes file transfers

### ISSUE THREAD

**Issue by yurivict** [Antox/Antox#408]
File transfers seem to work fine in 0.25.1. They were broken for a long time.
Please consider releasing 0.25.1.

**Comment by wiiaam** [comment]
It should be up now

**Comment by anon8675309** [comment]
Confirmed Antox 0.25.456 (15456) is in the Play store and file transfers are working beautifully.  I tested sending a picture from disk and one from the camera.  This issue can be closed.  Thanks @wiiaam
