### ISSUE TITLE
"Antox Crashed Tap to restart" loop after upgrade to 0.25.453

### ISSUE THREAD

**Issue by Chewie9999** [Antox/Antox#416]
I tried uninstalling it manually, and reinstalling it, but it still shows the same message.
This message appears both when I try and import my original .tox file and if I try to "Register" a new user.

My phone is a Fairphone 2 running android 5.1, patch level "5th December 2016", and v1.10.1 of the Fairphone software.

Please let me know how I can send more details about this problem.
Thanks,

**Comment by githubbantor** [comment]
Same here. Completely unusable.

loop:
Antox > rashed, tap to restart > tap > login menu > tap "login"

**Comment by githubbantor** [comment]
it never let user to configure their proxy. my wifi require proxy. this bug exist from last year. this must be high priority.

**Comment by zoff99** [comment]
@githubbantor please attach the crashlog file here (its on your SD card)
!!be careful it may contain sensitive data!!

**Comment by githubbantor** [comment]
@zoff99 would you email me antoxissue416@riseup.net so I can send these logs confidentially?

**Comment by wiiaam** [comment]
Is this the v7a issue? This should be fixed in the current update
