### ISSUE TITLE
ability not to import profile and work directly with selected .tox file

### ISSUE THREAD

**Issue by soredake** [Antox/Antox#421]
Like desktop clients do.

**Comment by wiiaam** [comment]
I don't understand, you can import tox files in the create account menu?

**Comment by soredake** [comment]
I can import, i do not want, i want to just open .tox file and decrypt to memory, like the desktop client do.

**Comment by SkyzohKey** [comment]
@wiiaam I guess he wants a button that allow to select a .tox file and connect with this one without having to import/save it in the Antox folder.

**Comment by wiiaam** [comment]
Dunno why its necessary, you can just delete the profile afterwards. Desktop clients can have this luxury because they have a more window population to add features like this in

**Comment by zoff99** [comment]
@soredake you can try https://github.com/zoff99/ToxAndroidRefImpl
