### ISSUE TITLE
[proposal] Change Antox icon.

### ISSUE THREAD

**Issue by SkyzohKey** [Antox/Antox#423]
Hey guys,

Today I just released the Tox icon for the Moka icon theme and I found that it might be cool for Antox to use it, as it looks more polished/mature.

### SVG (all sizes)
![Differents icon size](https://a.doko.moe/sepyfl.svg)

### Extra
With this icon, with doesn't need a blank border as it works perfectly on dark backgrounds.
![Dark background rendering](https://a.desu.sh/yxrwgm.png)

**Comment by SkyzohKey** [comment]
@wiiaam any guess about this ?

**Comment by zoff99** [comment]
this icon looks very "apple"-y
also it will not work so good on dark background home screens.

maybe tweak it a little towards material design guidelines?

**Comment by SkyzohKey** [comment]
I use this icon on desktop with dark background and it works just nice. eh.

**Comment by wetubeyou** [comment]
Can you make the background more lighter? #808080

**Comment by wiiaam** [comment]
It's a little too similar to the other client logos, its nice having something quite unique. Anyway not really planning on changing the icon, since its saved on a few webservers and would require a fair bit to change
