### ISSUE TITLE
cannot open project

### ISSUE THREAD

**Issue by afaideen** [Antox/Antox#430]
I tried to import it as soon as i finished downloading it but upon importing it android returned error
"Error:No such property: useAnt for class: org.gradle.api.tasks.scala.ScalaCompileOptions".
Android Studio i am using has version 2.3 the latest todate.

**Comment by zoff99** [comment]
please specifiy exactly how you open the project? attach some screenshots

**Comment by chrisfelesoid** [comment]
@afaideen Hi! I tried [this](https://github.com/xingda920813/gradle-android-scala-plugin). It works.
my envs:
Android Studio 3.0 Canary 6

gradle/wrapper/gradle-wrapper.properties
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-milestone-1-all.zip
```

app/build.gradle
```
        classpath ('com.android.tools.build:gradle:3.0.0-alpha6'){
            exclude module: 'proguard-gradle'
        }
        // compiled by subliun --------
        classpath 'com.github.xingda920813:gradle-android-scala-plugin:android-gradle-2.3.0'
        // compiled by subliun --------
```
