### ISSUE TITLE
Allow creation of new Quick Replies

### ISSUE THREAD

**Issue by SkyzohKey** [Antox/Antox#432]
Currently we are only able to edit the 5 ones pre-defined. Also, the sentences should be made translatable.

**Comment by subliun** [comment]
Does anyone really need more than five

**Comment by zoff99** [comment]
i count 4

![image](https://user-images.githubusercontent.com/6833516/33179240-00b36d7a-d069-11e7-9a9e-c35da5d06542.png)

**Comment by SkyzohKey** [comment]
@zoff99 
![](http://m.memegen.com/398by1.jpg)
