### ISSUE TITLE
Inline image widget needs to be polished

### ISSUE THREAD

**Issue by SkyzohKey** [Antox/Antox#437]
The current widget for inline image file transfers looks cluttered because too many useless informations are displayed.

![](https://a.doko.moe/tokbjr.png)

Why not remove all the texts beside the image and just display it in full scaled size ? Again, let's inspirate us from messenger.

**Comment by zoff99** [comment]
before the fields were mostly missing, or sometimes appearing from time to time.
it's "fixed" now

**Comment by SkyzohKey** [comment]
I mean the widget for inline images should be only the image, without all that garbage text. Average user mostly don't care about size, filename, etc. And for power user, we can add these informations in a pop-up when long clicking the image «long click -> Details -> filename, size, recv date, exif if any, etc)

**Comment by SkyzohKey** [comment]
It should exactly looks like this mockup:
![](https://camo.githubusercontent.com/17c99b1dad2bc00a9acbee699eb969353a27edd3/687474703a2f2f692e696d6775722e636f6d2f6a417047695a512e706e67)

**Comment by wiiaam** [comment]
Agreed, should have a long press option for details. This would only apply for images though, and possibly audio/video

**Comment by SkyzohKey** [comment]
:clap:
