### ISSUE TITLE
Please add Swedish translation

### ISSUE THREAD

**Issue by jony0008** [Antox/Antox#445]
The Swedish translation is finished, please add it to the next release.

**Comment by SkyzohKey** [comment]
Feel free to open a pull request with the translated .xml files. 🙃

**Comment by zoff99** [comment]
actually you should translate on transifex:

https://www.transifex.com/antox/antox/

**Comment by jony0008** [comment]
I have translated it on transifex already.

**Comment by zoff99** [comment]
@wiiaam needs to merge it then

**Comment by wiiaam** [comment]
Neither myself or @subliun have access to the transifex account. It was created when @markwinter ran the project and even he isn't sure who has access. Best thing to do would be creating a pull request

**Comment by jony0008** [comment]
#468

**Comment by wiiaam** [comment]
Merged #468
