### ISSUE TITLE
Offline Messaging is not possible.

### ISSUE THREAD

**Issue by NebelMe** [Antox/Antox#457]
I do not know if this is really a problem, but I think it is essential for a messenger.
Idea for Fix this: It should be possible to hide the app of the android task manager. So you can stay online.
Is this a right idea or didn't understand something?

**Comment by basiljose1** [comment]
Offline message for Android to IOS, Android to Desktop Applications is working but the same for Android to Android is not working 

if offline messaging is not supported by tox then how  Android to IOS, Android to Desktop Applications is getting work

**Comment by wiiaam** [comment]
Offline messaging is currently not implemented in toxcore. This feature is high on the priorities list though.
