### ISSUE TITLE
SVG icon

### ISSUE THREAD

**Issue by conrad-heimbold** [Antox/Antox#464]
Hi, I improved the svg icon for your app. You can find it here: https://gist.github.com/conrad-heimbold/8117367a79c8de2a739a3dfab35c7a29 

Feel free to change colors or the radius of the upper circles / sizes in general.

**Comment by wiiaam** [comment]
Currently we are not looking at changing the app icon, as it would require a lot of updating on other web servers. Plus the old one works fine

**Comment by yegortimoshenko** [comment]
This icon looks amazing! Could you reconsider it? I can send a pull request that updates all instances of the icon (`ic_launcher.png`) in this repo, and if any of the other places it's in are available as repos, can send pull requests to those as well.
