### ISSUE TITLE
[Question] Is there any version that works on android 2.3.6 and doesn't crash?

### ISSUE THREAD

**Issue by Monsterovich** [Antox/Antox#482]
Because the current version doesn't support old android.

**Comment by subliun** [comment]
You might be able to find an old apk somewhere but it is not advised as the tox protocol has likely had breaking changes since the last 2.3.6 release. Unfortunately the difficulty of supporting Android 2.3 meant that support had to be dropped.

**Comment by Monsterovich** [comment]
Well, found it. https://drive.google.com/open?id=19bi5eiYliPiAoUD6z9mI1nqMq5bQEzYD
