### ISSUE TITLE
 app Lose response

### ISSUE THREAD

**Issue by cws999** [Antox/Antox#512]
Antox version:0.8.2
Operating system:andrid
phone:vivo y75a

Issue
When I add a friend' ID , app Lose response

**Comment by zoff99** [comment]
@cws999 try https://f-droid.org/packages/com.zoffcc.applications.trifa/ for a more recent feature toxcore client

**Comment by cws999** [comment]
> @cws999 try https://f-droid.org/packages/com.zoffcc.applications.trifa/ for a more recent feature toxcore client

This app Can not Switch user .When do you add this feature?
