### ISSUE TITLE
Use Android Emoji

### ISSUE THREAD

**Issue by tedr56** [Antox/Antox#60]
Should decode smileys with Android Emojis

**Comment by Astonex** [comment]
Can you just clarify what you mean by this for me

**Comment by tedr56** [comment]
I think Android have integrated emojis.
Would be nice to use it in Antox

**Comment by ProMcTagonist** [comment]
Are you saying you want :) to be displayed as an emoji?

**Comment by 00firestar00** [comment]
Just curious if this is still an issue. Antox treats emojis the same way the Hangouts app does. Regular emoticons are not converted such as `:)` or `:/` but if you use an keyboard with emoji support, or paste in an emoji char it works just fine. The emojis even show up on uTox for windows
Tested on Android 4.1,4.4 and 5.1.

**Comment by RunningDroid** [comment]
I'm not sure if this is related to what @test56 wanted but on Android 5.0.1 with antox 0.23.93 when talking to toxic v.0.6.1_r1570 the emoji show up (on toxic) as stuff like "  ~_~X~@"
