### ISSUE TITLE
Support encrypted profiles

### ISSUE THREAD

**Issue by call5** [Antox/Antox#78]
i install antox and i try to import my qtox profil, but antox crash all time i try to import my profile 

 ![antox](https://i.imgur.com/XEsunWr.png)

**Comment by call5** [comment]
logcat https://paste.debian.net/hidden/826d6b5e/

**Comment by Astonex** [comment]
Is your qTox profile encrypted?

**Comment by call5** [comment]
yes

**Comment by DX37** [comment]
Delete password protection from your profile in qTox and export profile to file. Importing in Antox will work.

**Comment by Astonex** [comment]
https://github.com/subliun/Antox/pull/90 Once this is merged it will no longer crash but it will let you know encrypted profiles aren't supported

We're waiting on Tox4J to support encrypted profiles

**Comment by DX37** [comment]
Great :)

**Comment by yeppix** [comment]
are there any news?

**Comment by timofonic** [comment]
What about this?

**Comment by arkhan** [comment]
Please merge...

**Comment by subliun** [comment]
I'm waiting on a minor fix from tox4j

**Comment by arkhan** [comment]
+1

**Comment by wiiaam** [comment]
Now supported https://github.com/Antox/Antox/commit/6bec84a185f5dd7d158836c0ce975babb1b8adc2
