### ISSUE TITLE
[Regression] No way to set bootstrap node

### ISSUE THREAD

**Issue by zetok** [Antox/Antox#98]
Antox allowed to set custom bootstrap node, now it doesn't.

"reposting" here, since https://github.com/Astonex/Antox/issues/382 was closed.

**Comment by ProMcTagonist** [comment]
Allowing users to specify bootstrap nodes, however hidden in advanced menus the option is, is critical for the operation of the Tox network in bad circumstances where the main nodes are seized or shut down for whatever reason.

**Comment by wiiaam** [comment]
Feature added

**Comment by dvergeylen** [comment]
Hi there,

Thank you for this awesome feature. May I ask why we have to provide an IP when using custom bootstrap node?

https://github.com/Antox/Antox/blob/13808f937f80f6720830afc59c300b98e09df7ee/app/src/main/scala/chat/tox/antox/tox/ToxSingleton.scala#L151-L155

When iterating from the list https://nodes.tox.chat/json, some ipv4 fields are actually URLs. Providing an URL in the custom bootstrap field returns "Invalid IP address".

Do you know any way to achieve this?

**Comment by dvergeylen** [comment]
Opened a new issue [here](https://github.com/Antox/Antox/issues/487) as it *seems* bootstrap nodes  with an URL filled as IPv4 field (instead of a valid IP address) results in a parsing error (limiting number of possible bootstrap nodes).
